nodes:
  - id: 1
    name: "Central Park"
    lat: 40.785091
    lon: -73.968285
    connections: [2, 3, 4]
  - id: 2
    name: "Times Square"
    lat: 40.758896
    lon: -73.985130
    connections: [1, 3, 5]
  - id: 3
    name: "Empire State Building"
    lat: 40.748817
    lon: -73.985428
    connections: [1, 2, 6]
  - id: 4
    name: "The Metropolitan Museum of Art"
    lat: 40.779437
    lon: -73.963244
    connections: [1]  # Connecting back to Central Park
  - id: 5
    name: "Broadway Theatre"
    lat: 40.763758
    lon: -73.983488
    connections: [2]  # Connecting back to Times Square
  - id: 6
    name: "Madison Square Garden"
    lat: 40.750504
    lon: -73.993439
    connections: [3]  # Connecting back to Empire State Building
